---
- hosts: localhost 
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      pacman:
        update_cache:yes
      changed_when: False

  tasks:
    _include: tasks/packages.yml

