---
- name: Arch Installasjon
  hosts: localhost 
  connection: local
  become: yes

  tasks:
  - name: install packages
    pacman:
      name:
        - htop
        - tmux
        - vim-nox
        - emacs


  
